"""Primaryjoin added between Inventory and InventoryHistory fixed

Revision ID: 3784734005e7
Revises: 9b8b29713a4f
Create Date: 2025-05-17 01:42:44.183531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3784734005e7'
down_revision: Union[str, None] = '9b8b29713a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
