"""Primaryjoin added to inventory side in relation of Inventory and InventoryHistory

Revision ID: 51f4f12451cd
Revises: d2406e2d2957
Create Date: 2025-05-16 23:47:52.041798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f4f12451cd'
down_revision: Union[str, None] = 'd2406e2d2957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
