"""Foreign Keys defined between Inventory and InventoryHistory

Revision ID: 6788cc9e9cf9
Revises: 51f4f12451cd
Create Date: 2025-05-17 01:24:34.010171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6788cc9e9cf9'
down_revision: Union[str, None] = '51f4f12451cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
