"""Primaryjoin removed between Inventory and InventoryHistory fixed

Revision ID: 9b8b29713a4f
Revises: c073953b1589
Create Date: 2025-05-17 01:42:09.749008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8b29713a4f'
down_revision: Union[str, None] = 'c073953b1589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
