"""Bidirectional Relationship between Inventory and InventoryHistory fixed

Revision ID: c073953b1589
Revises: 6788cc9e9cf9
Create Date: 2025-05-17 01:29:55.880317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c073953b1589'
down_revision: Union[str, None] = '6788cc9e9cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
