"""Add inventory_id FK to history

Revision ID: f75ddf0f5bd8
Revises: 3784734005e7
Create Date: 2025-05-17 01:50:45.724153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75ddf0f5bd8'
down_revision: Union[str, None] = '3784734005e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_history', sa.Column('inventory_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_history', 'inventory', ['inventory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_history', type_='foreignkey')
    op.drop_column('inventory_history', 'inventory_id')
    # ### end Alembic commands ###
